const express = require('express');
// ...existing imports...
const twilioRoutes = require('./routes/twilioRoutes');

const app = express();
// ...existing middleware...
app.use('/api/twilio', twilioRoutes);
// ...existing code...